### ISSUE TITLE
iOS Build fails - Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by danielw92** [artoolkit/arunity5#141]
Hi everyone,

since issues #132 / #135 affected me, I tried getting the latest version of ARToolkit from the master branch here to work with Unity 5.5.1.
I cloned the repo and ran the share/packaging/ARUnity5-bin.sh script. Importing the created unitypackage already shows weird behavior:
![bildschirmfoto 2017-02-16 um 17 04 22](https://cloud.githubusercontent.com/assets/7038857/23029267/3799fe7a-f46a-11e6-8801-37868da2c2ff.png)
I'm not sure if I should be importing anything to the Unity application folder. If I do, it completely breaks Unity and only a complete reinstall of Unity fixed this.
Anyway, if I continue and import only files to the project folder, when I try to build one of the example scenes, Xcode shows me these errors:
![bildschirmfoto 2017-02-16 um 16 53 20](https://cloud.githubusercontent.com/assets/7038857/23029356/821e7750-f46a-11e6-81f3-eb29cf696415.png)
Unity is set to use IL2CPP, just in case that is relevant.
I'm really not sure if I might be doing something wrong or if there's a bug.
Any help would be appreciated.

**Comment by BoiseBaked** [comment]
I'm pretty sure I know what the problem is here but I need should sync up and make sure the solution works. I think it's a matter of adding some missing binary dependencies to the link stream in the Unity generated iOS XCode project. I'll get back to this later.

**Comment by BoiseBaked** [comment]
To fix the broken build is easy. BTW, you need to let us know which "example" iOS or Unity scene you're running. The ARTK5 APIs has a dependency on cURL and cURL has as a dependency on libz. I don't know when that started but something got rearranged recently. Anyways, to fix the Unity Build to iOS, open the Unity generated Xcode project, in the the Xcode IDE select the Unity-iPhone project folder and then the Unity-iPhone target in the Xcode main window. This displays all the Xcode project build and configuration menu items. Click "Build Phases" and twirl open "Link Binary With Libraries" and scroll to bottom of the list and click the '+' button. From the displayed list, scroll down to libz.tbd, select it and click the Add button. This fixes the "not found" symbols.

New problem, the app quickly abnormally aborts on startup before the camera is enabled and capturing:
2017-02-20 12:42:17.958557 demo[307:17907] [MC] Reading from public effective user settings.
2017-02-20 12:42:17.972721 demo[307:18027] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.

You guys can help with that.
Here's what I'm using:
  Xcode: Version 8.2.1 (8C1002)
  Unity Personal Edition: 5.5.0f3
  iPhone device being tested: iPhone 6, MG492LL/A
  ARTK5-Unity "example" scene (Unity App) being built and executed: "SimpleScene - which augments a cube over the recognized and tracker Hiro square marker.

Come on you brilliant iOS and Unity devs, tell me how to update the NSCameraUsageDescription key to get past the privacy abnormal termination.

**Comment by BoiseBaked** [comment]
OK, this was an easy one. In addition to all steps above, add these:
1) Before building to the Unity app to native iOS, after doing a "switch platform" to the "iOS" platform in the "Build Settings..." window, click "Players Settings" button. In the iOS "Player Settings..." window, open the "Other Settings" accordion menu, scroll down to the "Configuration" section and add text to the "Camera Usage Description" textbox. This text is used in addition to the user prompt for camera access permissions.
2) In the Unity build generated Xcode iOS project, open the Unity generated Xcode project, in the the Xcode IDE select the Unity-iPhone project folder and then the Unity-iPhone target in the Xcode main window. This exposes the Capabilities menu item in the main window. Click on Capabilities tab and turn off "Game Center". There's probably a way to do this from the Unity "Build Settings..." iOS "Players Settings."
