### ISSUE TITLE
ARToolkit and UWP 10

### ISSUE THREAD

**Issue by tenguzame** [artoolkit/arunity5#144]
Hi all,
I'm trying to develop a very simple AR project with Unity and ARToolkit. I downloaded all the required SDKs and the ARToolkit plugin for Unity (I'm using version 5.5 for 32-bit Windows 10 system) and prepared a scene just as the tutorial requires. When I try and build it, though, I keep getting an error "Error building player because script class layout is incompatible between the editor and the player." Also, when I check the Plugin folder I see no ARM folder inside.
Does ARToolkit support the development of apps for ARM devices?

-MikeT

**Comment by ThorstenBux** [comment]
Hi there,
just to understand:
- You are developing on a Windows PC?
- You are targeting a Android device?
- Your Android device is ARM?

Unity itself only supports armeabi-v7a and x86 for Android.

I try and understand your setup a bit better in order to help you

**Comment by tenguzame** [comment]
Dear Thorsten,
Thanks for the input. I'm trying to develop on a Windows PC (Windows 10 64-bit) and targeting my mobile phone (a Nokia Lumia 540), which is an ARM device with an ARM Cortex A7 chip.

**Comment by ThorstenBux** [comment]
Hm, I just did that recently and it worked well. 
Let us ask @BoiseBaked

**Comment by BoiseBaked** [comment]
It appears that tenguzame is developing on Windows 10 Desktop for a Windows 10 Phone. The problem is that we haven't updated the Windows Phone for Unity plugin in a very longtime. In fact, when we built the last Windows Phone for Unity plugin, I don't think Windows 10 was even released. I believe the last build was targeting Windows 8.1 Universal, built with Visual Studio 2013. UWP was in its infancy. We're trying to catch up and support Windows 10 using assets built with Visual Studio 2017. Another complication is that native Windows-wise, the Phone platforms between Windows 7, Windows 8, Windows 8.1 and Windows 10 are radically different. And of course, ARToolKit depends greatly on the native platform.

**Comment by ThorstenBux** [comment]
Is your phone still at Windows 8.1 or at Windows 10? @tenguzame ?

**Comment by tenguzame** [comment]
My phone currently hosts a Windows 10 system.
