### ISSUE TITLE
Matrix code type 3x3 Parity - not working?

### ISSUE THREAD

**Issue by clavis-magna** [artoolkit/arunity5#157]
Is there something else I need to set in the 'Ar Controller' script besides 'Matrix Code Type' to 'AR_MATRIX_CODE_3x3_PARITY65' to get the 'Matrix code 3x3 with parity' markers to be recognised by Unity ARToolkit (Unity5.5, AR Toolkit 5.3.2)

Project works fine with 'AR_MATRIX_CODE_3x3' and the 'Matrix code 3x3' marker set, but as I have under 32 markers, I wanted to use Parity65 for more accuracy, but it fails to recognise markers from the 'Matrix code 3x3 with parity' set with the 'AR_MATRIX_CODE_3x3_PARITY65' setting

**Comment by philip-lamb** [comment]
If it is working with 3x3 matrix code, that should be the only change required. If you were setting it up from scratch, you'd need to check that the pattern detection mode was AR_MATRIX_CODE_DETECTION and that the border size was the same as you're using (default 0.25).

**Comment by clavis-magna** [comment]
I have all those settings. Steps to reproduce.

1. fresh unity project (Unity 5.5)
2. import Unity package from here : https://artoolkit.org/download-artoolkit-sdk
3. run 'BarcodeScene'
4. Square Marker '0' tracks and shows red cube
5. stop 'BarcodeScene'
6. change 'Matrix Code Type'  to 'AR_MATRIX_CODE_3x3_PARITY65'
7. Square Marker '0' no longer tracks

markers printed directly from 'ARUnity5-5.3.2-tools-osx'

(have tried with other markers from both sets)

**Comment by clavis-magna** [comment]
The issue is with the version packaged on the ARToolkit site : https://artoolkit.org/download-artoolkit-sdk. It is working fine from the version here.

**Comment by ThorstenBux** [comment]
Yeah, it has been some time since we updated the downloadable version on the website. 

If I understand you correctly the solution is to use the version from GitHub.

Thanks for sharing

**Comment by lenaschimmel** [comment]
I'm currently running into the same problem and tried to apply the solution from @clavis-magna. But it seems not to work for me.

Maybe I did not understand correctly what's meant by 

> It is working fine from the version here.

I cloned `https://github.com/artoolkit/arunity5.git` (currently at [this commit](https://github.com/artoolkit/arunity5/commit/1877ac3571167e90aeb1f4ad4eb269cb29729d92)) and copied everything from [src/Unity/Assets/Plugins](https://github.com/artoolkit/arunity5/tree/master/src/Unity/Assets/Plugins) into the `Assets/Plugins/` folder in my Project, which includes a lot of `dll` files.

Note: I had to remove the `Metro` folder because Unity tried to load all the dlls from there, even though not a single one matches my system's architecture (`x86_64` on Windows 10). The remaining `.dll`-Files (`Assets/Plugins/x86_64/ARWrapper.dll` and `Assets/Plugins/x86_64/ARVideo.dll`) were fully identical to the old files, and of course did not work with Parity enabled.
