### ISSUE TITLE
Nexus5X camera flipped

### ISSUE THREAD

**Issue by Zappelphilipp** [artoolkit/arunity5#77]
The nexus 5x device has the camera orientation sensor mounted in an uncommon way. That's why the image will result upside down in unity. I know that ARToolkit can flip the video plane, but this does not effect the video input, for example when using google cardboard. So the stream itself stays unflipped. To fix this, the "new" camera API should be used. Is there an easy workaround to fix this temporarily?
further informations: [https://www.reddit.com/r/Android/comments/3rjbo8/nexus5x_marshmallow_camera_problem/](url)

**Comment by JScott** [comment]
Flipping vertically and horizontally on the AR Controller script seemed to at least visually fix this issue for me. That solution probably breaks every other phone though so I'm interested in seeing the correct API implemented as well.

**Comment by BoiseBaked** [comment]
The camera image orientation issue, as Zappelphillipp stated, is an issue on some Android hardware platforms, i.e. a difference between camera sensor and the devices' natural/default orientation. There are many stackoverflow and blogs that discuss how to detect the difference, if there is a differences, and compensate for the detected difference. In most cases, the fix is simply ask the device for its model and apply a hardcode fix specific to the model.
